image: local-registry.inner.buaaoo.top/library/java:8u201-edu

stages:
  - demo
  - test
  - submit

variables:
  CI: 'true'
  ZIP_URL: 'https://releases.buaaoo.top/homework_2_specs/specs-homework-2-1.1-raw-jar-with-dependencies.zip'
  ZIP_NAME: 'specs-homework-2-1.1-raw-jar-with-dependencies'
  UNZIP_SPEC1_PASSWORD: '0X9HihGH6lQm/Y2LX72AvqePKDDDiAqv9gotnMvn684='
  ZIP_DIRECTORY: 'spec'
  JAR_NAME: 'specs-homework-2-1.1-raw-jar-with-dependencies'
  SPEC_GROUP_ID: 'com.fileutils'
  SPEC_ARTIFACT_ID: 'specs'
  SPEC_VERSION: '2.1.1'


before_script:
  - java -version
  - javac -version
  - mvn -v

run_demo:
  stage: demo
  script:
    - echo 'this is my demo'  # place your demo here

run_unittest:
  stage: test
  script:
    - echo "this is test"
    - apt-get install zip -y
    - curl ${ZIP_URL} --output ${ZIP_NAME}
    - unzip -P ${UNZIP_SPEC1_PASSWORD} ${ZIP_NAME} -d ${ZIP_DIRECTORY}
    - mv ${ZIP_DIRECTORY}/*.jar ${JAR_NAME}
    - mvn install:install-file -Dfile=${JAR_NAME} -DgroupId=${SPEC_GROUP_ID} -DartifactId=${SPEC_ARTIFACT_ID} -Dversion=${SPEC_VERSION} -Dpackaging=jar
    - mvn compile
    - mvn cobertura:cobertura
    - mvn cobertura:dump-datafile
    - cp -r target/site/cobertura test_result
  artifacts:
    name: test_result
    paths:
      - test_result/
    expire_in: 1 yrs
  coverage: '/coverage line-rate="\d+/'

submit_code:
  stage: submit
  script:
    - pjcourse config add judge  # register the judge service
    - pjcourse config info judge  # try connect to the judge service
    - pjcourse homework list judge  # get to know all the available homeworks
    - pjcourse homework submit judge homework_3  # submit your homework (homework_1 is the name of homework, may be changed when 2st, 3rd homeworks)
    - pjcourse homework history judge homework_3  # get your submit history


